dataset_type: 'structure_dataset'
df_path: '/mnt/HDD36/pavel/COPRA/raw_data/valentina_clean_data_test_set/meta.csv'
batch_size: 16
data_root: '/mnt/HDD36/pavel/COPRA/raw_data/valentina_clean_data_test_set/pdbs_with_chains'
num_workers: 2
col_prot_name: 'name'
col_prot_chain: 'prot_chains'
col_na_chain: 'rna_chains'
col_label: 'energy'
pin_memory: True
prepared_dir: '/mnt/HDD36/pavel/COPRA/processed_data/valentina_clean_data_test_set/cached'
loss_type: regression
strategy: separate
inna_weights: '../InNA/model/best_val0.3775_step72000.pth'
inna_repo_path: '../InNA'
atom_resolution: backbone

transform:
  - type: select_atom
    resolution: backbone
  - type: selected_region_with_distmap
    patch_size: 256
  - type: subtract_center_of_mass