output_dir: './outputs/esm2rinalmo_650M/test_struct/best_model'
gpus:
  - 0

ckpts: 
  - ./weights/CoPRA_5fold/CoPRA_fold0.ckpt
  - ./weights/CoPRA_5fold/CoPRA_fold1.ckpt
  - ./weights/CoPRA_5fold/CoPRA_fold2.ckpt
  - ./weights/CoPRA_5fold/CoPRA_fold3.ckpt
  - ./weights/CoPRA_5fold/CoPRA_fold4.ckpt

run_name: 'esm2rinalmo_test_best'
logger: csv
num_folds: 5